name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


  services:

    postgres:
      image: postgres
      env:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: simple_bank
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        id: go

      - uses: actions/checkout@v3

      - name: Run migrateup
        run: make migrateup

      - name: Test
        run: make test
